//verilog code for arthmetic logical unit. performs the operations based on instructions given

module arithmetic_logic_unit(
    input [31:0] src1,          //value in source register 1
    input [31:0] src2,          //value in source register 2
    input [5:0] alu_control,    //control signal generated for ALU operations by control unit
    input [31:0] imm_address,    //immediate address generated by IMM_GEN sent here from top module -> DPU -> ALU
    output reg [31:0] result,    //result of ALU operations
    output reg beq,                     
    output reg bneq,                     
    output reg bge,                      
    output reg blt
    );

    always @ (alu_control)
    begin

        beq=0;
        bneq=0;
        bge=0;
        blt=0;
        jump=0;

        case (alu_control)

// R TYPE INSTRUCTIONS
        6'b000000:              // ADD OPERATION
        result= src1+src2;

        6'b000001:              // SUB OPERATION
        result= src1-src2;

        6'b000010:              // SLL OPERATION
        result= src1<<src2;

        6'b000011:              // SLT OPERATION
        result= ($signed(src1)<$signed(src2))?32'b1:32'b0;

        6'b000100:              // SLTU OPERATION
        result= (src1 < src2)? 32'b1:32'b0;

        6'b000101:              // XOR OPERATION
        result= src1 ^ src2;

        6'b000110:              // SRL OPERATION
        result= src2 >> src1;

        6'b000111:              // SRA OPERATION
        result= ($signed(src2)) >>> src1;

        6'b001000:              // OR OPERATION
        result= src1 | src2;

        6'b001001:              // AND OPERATION
        result= src1 & src2;

// I TYPE INSTRUCTIONS
        6'b001010:              // ADDI OPERATION
        result= src1+imm_address;

        6'b001011:              // SLLI OPERATION
        result= src1 << imm_address;

        6'b001100:              // SLTI OPERATION
        result= ($signed(src1) < $signed(imm_address))? 32'b1:32'b0;

        6'b001101:              // SLTUI OPERATION
        result= (src1 < imm_address)? 32'b1: 32'b0;

        6'b001110:              // XORI OPERATION
        result= src1 ^ imm_address;

        6'b001111:              // SRLI OPERATION
        result= src1 >> imm_address;

        6'b010000:              // SRAI OPERATION
        result= ($signed)src1 >>> imm_address;

        6'b010001:              // ORI OPERATION
        result= src1 | imm_address;

        6'b010010:              // ANDI OPERATION
        result= src1 & imm_address;

// L TYPE INSTRUCTIONS
        6'b010011,              // LB OPERATION
        6'b010100,              // LH OPERATION
        6'b010101,              // LW OPERATION
        6'b010110,              // LBU OPERATION
        6'b010111:              // LHU OPERATION
        result= src1+imm_address;
        // there is only calculation of memory address from where to load into register

// S TYPE INSTRUCTIONS
        6'b011000,              // SB OPERATION
        6'b011001,              // SH OPERATION
        6'b011010:              // SW OPERATION
        result= src1+imm_address;
        // there is only calculation of memory address to store data from register

// B TYPE INSTRUCTIONS
        6'b011011:              // BEQ OPERATION
        begin
            if(src1==src2)
            beq=1;
        end

        6'b011100:              // BNE OPERATION
        begin
            if(src1!=src2)
            bneq=1;
        end

        6'b011101:              // BLT OPERATION
        begin
            if ($signed(src1) < $signed(src2))
            blt=1;
        end

        6'b011110:              // BGE OPERATION
        begin
            if($signed(src1) >= $signed(src2))
            bge=1;
        end

        6'b011111:              // BLTU OPERATION
        begin
            if(src1<src2)
            blt=1;
        end

        6'b100000:              // BGEU OPERATION
        begin
            if(src1>=src2)
            bge=1;
        end

// J TYPE INSTRUCTIONS
        6'b100001:              // JAL OPERATION
        begin
            // no operation required as jump address caculation is done in instruction fetch unit
        end

// U TYPE INSTRUCTIONS
        6'b100010:              // LUI OPERATION
        result= imm_address;
        
        endcase
    end
endmodule